baseURL = 'localhost'
languageCode = 'pt-BR'
title = 'Jason Henrique'
theme = 'gokarna'

description = "Um site onde compartilho sobre tecnologia"
author = "Jason Henrique Martins Rodrigues"

[params]
  logo = "images/logo.png"
  primaryColor = "#3498db"
  secondaryColor = "#000034"
  enableSidebar = false
  darkMode = true
  paginate = 5
  

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name       = "Posts"
  url        = "/posts"
  weight     = 2

[[menu.main]]
  name       = "About"
  url        = "/about/"
  weight     = 3

[[menu.main]]
  name       = "Linkedin"
  url        = "https://www.linkedin.com/in/jasonhenrique/"
  weight     = 4

[[menu.main]]
  name       = "Certifications"
  url        = "https://www.credly.com/users/jason-henrique/"
  weight     = 5

[[menu.main]]
  name       = "Github"
  url        = "https://github.com/jjasonhenrique"
  weight     = 6





