baseURL = 'localhost'
languageCode = 'pt-BR'
title = 'Jason Henrique'
theme = 'gokarna'


author = "Jason Henrique Martins Rodrigues"

[params]
  #description = "Um site onde compartilho sobre tecnologia principalmente sobre kubernetes e AWS."
  showPostsOnHomePage = 4
  numberPostsOnHomePage = 8
  primaryColor = "#3498db"
  secondaryColor = "#000034"
  enableSidebar = true
  darkMode = true
  paginate = 5
  togglePreviousAndNextButtons = true
  displayReadingTime = true
  
  socialIcons = [
    {name = "github", url = "https://github.com/jjasonhenrique"},
    {name = "linkedin", url = "https://www.linkedin.com/in/jasonhenrique/"},
  ]


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name       = "Posts"
  url        = "/posts"
  weight     = 2

[[menu.main]]
  name       = "Projects"
  url        = "https://github.com/jjasonhenrique?tab=repositories"
  weight     = 3

[[menu.main]]
  name       = "Certifications"
  url        = "https://www.credly.com/users/jason-henrique/"
  weight     = 4







